server:
  port: 8080

spring:
  mvc:
    log-resolved-exception: false
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(zjrMv7n63dLMOj+lfQMRcDC3Rg0UZ3z0kJmPtz8s++o=)
    password: ENC(jAgUNikPZKgK0nedflqwrlPVR/X1W7zvX+spbrxhhO4=)
    properties:
      mail.smtp.starttls.enable: true
      mail.smtp.auth: true

cors:
  allow:
    origins: http://localhost:3000